version: '2.1'

services:
  user:
    build: .
    volumes:
      - .:/app:rw
    ports:
      - 8082:8082
    environment:
      ENV: development
      HOST: 0.0.0.0
      PORT: 8082
      GUNICORN_BIND: 0.0.0.0:8082
      # user_db credentials
      USER_DB_USERNAME: user
      USER_DB_PASSWORD: password
      USER_DB_HOST: postgres
      USER_DB_PORT: 5432
      USER_DB_DATABASE: user_db
    depends_on:
      postgres:
        condition: service_started

  postgres:
    extends:
      file: ../db_images/postgres/docker-compose.yml
      service: postgres

volumes:
  postgres_data:
    driver: local
